name: Notify PR Author

on:
  pull_request:
    types: [opened, reopened, ready_for_review]

jobs:
  notify:
    runs-on: ubuntu-latest

    steps:
      - name: Comentar no Pull Request
        uses: actions/github-script@v7
        with:
          script: |
            const prAuthor = context.payload.pull_request.user.login;
            const prNumber = context.payload.pull_request.number;
            const body = `👋 Olá @${prAuthor}, o teu Pull Request foi criado/reaberto.`;
            await github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: prNumber,
              body
            });
